DROP TABLE IF EXISTS meals CASCADE;

CREATE TABLE meals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  prep_time INTEGER NOT NULL,
  date_added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  added_by_user INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);