DROP TABLE IF EXISTS users_meals CASCADE;

CREATE TABLE users_meals (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  meal_id INTEGER REFERENCES meals(id) ON DELETE CASCADE NOT NULL,
  last_eaten TIMESTAMP WITH TIME ZONE,
  rating INTEGER DEFAULT 0
);